module Day11Spec where

import Day11
import Day11 (Octopus (Octopus, energy), Position (Position))
import Test.Hspec

testInput = "5483143223\n2745854711\n5264556173\n6141336146\n6357385478\n4167524645\n2176841721\n6882881134\n4846848554\n5283751526"

spec :: Spec
spec = do
  it "parseInput" $ do
    parseInput testInput
      `shouldBe` [ [5, 4, 8, 3, 1, 4, 3, 2, 2, 3],
                   [2, 7, 4, 5, 8, 5, 4, 7, 1, 1],
                   [5, 2, 6, 4, 5, 5, 6, 1, 7, 3],
                   [6, 1, 4, 1, 3, 3, 6, 1, 4, 6],
                   [6, 3, 5, 7, 3, 8, 5, 4, 7, 8],
                   [4, 1, 6, 7, 5, 2, 4, 6, 4, 5],
                   [2, 1, 7, 6, 8, 4, 1, 7, 2, 1],
                   [6, 8, 8, 2, 8, 8, 1, 1, 3, 4],
                   [4, 8, 4, 6, 8, 4, 8, 5, 5, 4],
                   [5, 2, 8, 3, 7, 5, 1, 5, 2, 6]
                 ]

  it "octopuses" $ do
    octopuses [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
      `shouldBe` [ Octopus {position = Position {x = 0, y = 0}, energy = 1},
                   Octopus {position = Position {x = 1, y = 0}, energy = 2},
                   Octopus {position = Position {x = 2, y = 0}, energy = 3},
                   Octopus {position = Position {x = 0, y = 1}, energy = 4},
                   Octopus {position = Position {x = 1, y = 1}, energy = 5},
                   Octopus {position = Position {x = 2, y = 1}, energy = 6},
                   Octopus {position = Position {x = 0, y = 2}, energy = 7},
                   Octopus {position = Position {x = 1, y = 2}, energy = 8},
                   Octopus {position = Position {x = 2, y = 2}, energy = 9}
                 ]
    octopuses [[1, 1, 1, 1, 1], [1, 9, 9, 9, 1], [1, 9, 1, 9, 1], [1, 9, 9, 9, 1], [1, 1, 1, 1, 1]]
      `shouldBe` [ Octopus {position = Position {x = 0, y = 0}, energy = 1},
                   Octopus {position = Position {x = 1, y = 0}, energy = 1},
                   Octopus {position = Position {x = 2, y = 0}, energy = 1},
                   Octopus {position = Position {x = 3, y = 0}, energy = 1},
                   Octopus {position = Position {x = 4, y = 0}, energy = 1},
                   Octopus {position = Position {x = 0, y = 1}, energy = 1},
                   Octopus {position = Position {x = 1, y = 1}, energy = 9},
                   Octopus {position = Position {x = 2, y = 1}, energy = 9},
                   Octopus {position = Position {x = 3, y = 1}, energy = 9},
                   Octopus {position = Position {x = 4, y = 1}, energy = 1},
                   Octopus {position = Position {x = 0, y = 2}, energy = 1},
                   Octopus {position = Position {x = 1, y = 2}, energy = 9},
                   Octopus {position = Position {x = 2, y = 2}, energy = 1},
                   Octopus {position = Position {x = 3, y = 2}, energy = 9},
                   Octopus {position = Position {x = 4, y = 2}, energy = 1},
                   Octopus {position = Position {x = 0, y = 3}, energy = 1},
                   Octopus {position = Position {x = 1, y = 3}, energy = 9},
                   Octopus {position = Position {x = 2, y = 3}, energy = 9},
                   Octopus {position = Position {x = 3, y = 3}, energy = 9},
                   Octopus {position = Position {x = 4, y = 3}, energy = 1},
                   Octopus {position = Position {x = 0, y = 4}, energy = 1},
                   Octopus {position = Position {x = 1, y = 4}, energy = 1},
                   Octopus {position = Position {x = 2, y = 4}, energy = 1},
                   Octopus {position = Position {x = 3, y = 4}, energy = 1},
                   Octopus {position = Position {x = 4, y = 4}, energy = 1}
                 ]
    octopuses [[3, 4, 5, 4, 3], [4, 0, 0, 0, 4], [5, 0, 0, 0, 5], [4, 0, 0, 0, 4], [3, 4, 5, 4, 3]]
      `shouldBe` [ Octopus {position = Position {x = 0, y = 0}, energy = 3},
                   Octopus {position = Position {x = 1, y = 0}, energy = 4},
                   Octopus {position = Position {x = 2, y = 0}, energy = 5},
                   Octopus {position = Position {x = 3, y = 0}, energy = 4},
                   Octopus {position = Position {x = 4, y = 0}, energy = 3},
                   Octopus {position = Position {x = 0, y = 1}, energy = 4},
                   Octopus {position = Position {x = 1, y = 1}, energy = 0},
                   Octopus {position = Position {x = 2, y = 1}, energy = 0},
                   Octopus {position = Position {x = 3, y = 1}, energy = 0},
                   Octopus {position = Position {x = 4, y = 1}, energy = 4},
                   Octopus {position = Position {x = 0, y = 2}, energy = 5},
                   Octopus {position = Position {x = 1, y = 2}, energy = 0},
                   Octopus {position = Position {x = 2, y = 2}, energy = 0},
                   Octopus {position = Position {x = 3, y = 2}, energy = 0},
                   Octopus {position = Position {x = 4, y = 2}, energy = 5},
                   Octopus {position = Position {x = 0, y = 3}, energy = 4},
                   Octopus {position = Position {x = 1, y = 3}, energy = 0},
                   Octopus {position = Position {x = 2, y = 3}, energy = 0},
                   Octopus {position = Position {x = 3, y = 3}, energy = 0},
                   Octopus {position = Position {x = 4, y = 3}, energy = 4},
                   Octopus {position = Position {x = 0, y = 4}, energy = 3},
                   Octopus {position = Position {x = 1, y = 4}, energy = 4},
                   Octopus {position = Position {x = 2, y = 4}, energy = 5},
                   Octopus {position = Position {x = 3, y = 4}, energy = 4},
                   Octopus {position = Position {x = 4, y = 4}, energy = 3}
                 ]

  it "step" $
    do
      step
        [ Octopus {position = Position {x = 0, y = 0}, energy = 1},
            Octopus {position = Position {x = 1, y = 0}, energy = 1},
            Octopus {position = Position {x = 2, y = 0}, energy = 1},
            Octopus {position = Position {x = 3, y = 0}, energy = 1},
            Octopus {position = Position {x = 4, y = 0}, energy = 1},
            Octopus {position = Position {x = 0, y = 1}, energy = 1},
            Octopus {position = Position {x = 1, y = 1}, energy = 1},
            Octopus {position = Position {x = 2, y = 1}, energy = 1},
            Octopus {position = Position {x = 3, y = 1}, energy = 1},
            Octopus {position = Position {x = 4, y = 1}, energy = 1},
            Octopus {position = Position {x = 0, y = 2}, energy = 1},
            Octopus {position = Position {x = 1, y = 2}, energy = 1},
            Octopus {position = Position {x = 2, y = 2}, energy = 1},
            Octopus {position = Position {x = 3, y = 2}, energy = 1},
            Octopus {position = Position {x = 4, y = 2}, energy = 1},
            Octopus {position = Position {x = 0, y = 3}, energy = 1},
            Octopus {position = Position {x = 1, y = 3}, energy = 1},
            Octopus {position = Position {x = 2, y = 3}, energy = 1},
            Octopus {position = Position {x = 3, y = 3}, energy = 1},
            Octopus {position = Position {x = 4, y = 3}, energy = 1},
            Octopus {position = Position {x = 0, y = 4}, energy = 1},
            Octopus {position = Position {x = 1, y = 4}, energy = 1},
            Octopus {position = Position {x = 2, y = 4}, energy = 1},
            Octopus {position = Position {x = 3, y = 4}, energy = 1},
            Octopus {position = Position {x = 4, y = 4}, energy = 1}
          ]
        `shouldBe` [ Octopus {position = Position {x = 0, y = 0}, energy = 2},
                       Octopus {position = Position {x = 1, y = 0}, energy = 2},
                       Octopus {position = Position {x = 2, y = 0}, energy = 2},
                       Octopus {position = Position {x = 3, y = 0}, energy = 2},
                       Octopus {position = Position {x = 4, y = 0}, energy = 2},
                       Octopus {position = Position {x = 0, y = 1}, energy = 2},
                       Octopus {position = Position {x = 1, y = 1}, energy = 2},
                       Octopus {position = Position {x = 2, y = 1}, energy = 2},
                       Octopus {position = Position {x = 3, y = 1}, energy = 2},
                       Octopus {position = Position {x = 4, y = 1}, energy = 2},
                       Octopus {position = Position {x = 0, y = 2}, energy = 2},
                       Octopus {position = Position {x = 1, y = 2}, energy = 2},
                       Octopus {position = Position {x = 2, y = 2}, energy = 2},
                       Octopus {position = Position {x = 3, y = 2}, energy = 2},
                       Octopus {position = Position {x = 4, y = 2}, energy = 2},
                       Octopus {position = Position {x = 0, y = 3}, energy = 2},
                       Octopus {position = Position {x = 1, y = 3}, energy = 2},
                       Octopus {position = Position {x = 2, y = 3}, energy = 2},
                       Octopus {position = Position {x = 3, y = 3}, energy = 2},
                       Octopus {position = Position {x = 4, y = 3}, energy = 2},
                       Octopus {position = Position {x = 0, y = 4}, energy = 2},
                       Octopus {position = Position {x = 1, y = 4}, energy = 2},
                       Octopus {position = Position {x = 2, y = 4}, energy = 2},
                       Octopus {position = Position {x = 3, y = 4}, energy = 2},
                       Octopus {position = Position {x = 4, y = 4}, energy = 2}
                     ]

      step
        [ Octopus {position = Position {x = 0, y = 0}, energy = 1},
            Octopus {position = Position {x = 1, y = 0}, energy = 1},
            Octopus {position = Position {x = 2, y = 0}, energy = 1},
            Octopus {position = Position {x = 3, y = 0}, energy = 1},
            Octopus {position = Position {x = 4, y = 0}, energy = 1},
            Octopus {position = Position {x = 0, y = 1}, energy = 1},
            Octopus {position = Position {x = 1, y = 1}, energy = 1},
            Octopus {position = Position {x = 2, y = 1}, energy = 1},
            Octopus {position = Position {x = 3, y = 1}, energy = 1},
            Octopus {position = Position {x = 4, y = 1}, energy = 1},
            Octopus {position = Position {x = 0, y = 2}, energy = 1},
            Octopus {position = Position {x = 1, y = 2}, energy = 1},
            Octopus {position = Position {x = 2, y = 2}, energy = 9},
            Octopus {position = Position {x = 3, y = 2}, energy = 1},
            Octopus {position = Position {x = 4, y = 2}, energy = 1},
            Octopus {position = Position {x = 0, y = 3}, energy = 1},
            Octopus {position = Position {x = 1, y = 3}, energy = 1},
            Octopus {position = Position {x = 2, y = 3}, energy = 1},
            Octopus {position = Position {x = 3, y = 3}, energy = 1},
            Octopus {position = Position {x = 4, y = 3}, energy = 1},
            Octopus {position = Position {x = 0, y = 4}, energy = 1},
            Octopus {position = Position {x = 1, y = 4}, energy = 1},
            Octopus {position = Position {x = 2, y = 4}, energy = 1},
            Octopus {position = Position {x = 3, y = 4}, energy = 1},
            Octopus {position = Position {x = 4, y = 4}, energy = 1}
          ]
        `shouldBe` [ Octopus {position = Position {x = 0, y = 0}, energy = 2},
                       Octopus {position = Position {x = 1, y = 0}, energy = 2},
                       Octopus {position = Position {x = 2, y = 0}, energy = 2},
                       Octopus {position = Position {x = 3, y = 0}, energy = 2},
                       Octopus {position = Position {x = 4, y = 0}, energy = 2},
                       Octopus {position = Position {x = 0, y = 1}, energy = 2},
                       Octopus {position = Position {x = 1, y = 1}, energy = 3},
                       Octopus {position = Position {x = 2, y = 1}, energy = 3},
                       Octopus {position = Position {x = 3, y = 1}, energy = 3},
                       Octopus {position = Position {x = 4, y = 1}, energy = 2},
                       Octopus {position = Position {x = 0, y = 2}, energy = 2},
                       Octopus {position = Position {x = 1, y = 2}, energy = 3},
                       Octopus {position = Position {x = 2, y = 2}, energy = 10},
                       Octopus {position = Position {x = 3, y = 2}, energy = 3},
                       Octopus {position = Position {x = 4, y = 2}, energy = 2},
                       Octopus {position = Position {x = 0, y = 3}, energy = 2},
                       Octopus {position = Position {x = 1, y = 3}, energy = 3},
                       Octopus {position = Position {x = 2, y = 3}, energy = 3},
                       Octopus {position = Position {x = 3, y = 3}, energy = 3},
                       Octopus {position = Position {x = 4, y = 3}, energy = 2},
                       Octopus {position = Position {x = 0, y = 4}, energy = 2},
                       Octopus {position = Position {x = 1, y = 4}, energy = 2},
                       Octopus {position = Position {x = 2, y = 4}, energy = 2},
                       Octopus {position = Position {x = 3, y = 4}, energy = 2},
                       Octopus {position = Position {x = 4, y = 4}, energy = 2}
                     ]

      step
        [ Octopus {position = Position {x = 0, y = 0}, energy = 1},
          Octopus {position = Position {x = 1, y = 0}, energy = 1},
          Octopus {position = Position {x = 2, y = 0}, energy = 1},
          Octopus {position = Position {x = 3, y = 0}, energy = 1},
          Octopus {position = Position {x = 4, y = 0}, energy = 1},
          Octopus {position = Position {x = 0, y = 1}, energy = 1},
          Octopus {position = Position {x = 1, y = 1}, energy = 9},
          Octopus {position = Position {x = 2, y = 1}, energy = 9},
          Octopus {position = Position {x = 3, y = 1}, energy = 9},
          Octopus {position = Position {x = 4, y = 1}, energy = 1},
          Octopus {position = Position {x = 0, y = 2}, energy = 1},
          Octopus {position = Position {x = 1, y = 2}, energy = 9},
          Octopus {position = Position {x = 2, y = 2}, energy = 1},
          Octopus {position = Position {x = 3, y = 2}, energy = 9},
          Octopus {position = Position {x = 4, y = 2}, energy = 1},
          Octopus {position = Position {x = 0, y = 3}, energy = 1},
          Octopus {position = Position {x = 1, y = 3}, energy = 9},
          Octopus {position = Position {x = 2, y = 3}, energy = 9},
          Octopus {position = Position {x = 3, y = 3}, energy = 9},
          Octopus {position = Position {x = 4, y = 3}, energy = 1},
          Octopus {position = Position {x = 0, y = 4}, energy = 1},
          Octopus {position = Position {x = 1, y = 4}, energy = 1},
          Octopus {position = Position {x = 2, y = 4}, energy = 1},
          Octopus {position = Position {x = 3, y = 4}, energy = 1},
          Octopus {position = Position {x = 4, y = 4}, energy = 1}
        ] `shouldBe` [ Octopus {position = Position {x = 0, y = 0}, energy = 3},
                     Octopus {position = Position {x = 1, y = 0}, energy = 4},
                     Octopus {position = Position {x = 2, y = 0}, energy = 5},
                     Octopus {position = Position {x = 3, y = 0}, energy = 4},
                     Octopus {position = Position {x = 4, y = 0}, energy = 3},
                     Octopus {position = Position {x = 0, y = 1}, energy = 4},
                     Octopus {position = Position {x = 1, y = 1}, energy = 10},
                     Octopus {position = Position {x = 2, y = 1}, energy = 10},
                     Octopus {position = Position {x = 3, y = 1}, energy = 10},
                     Octopus {position = Position {x = 4, y = 1}, energy = 4},
                     Octopus {position = Position {x = 0, y = 2}, energy = 5},
                     Octopus {position = Position {x = 1, y = 2}, energy = 10},
                     Octopus {position = Position {x = 2, y = 2}, energy = 10},
                     Octopus {position = Position {x = 3, y = 2}, energy = 10},
                     Octopus {position = Position {x = 4, y = 2}, energy = 5},
                     Octopus {position = Position {x = 0, y = 3}, energy = 4},
                     Octopus {position = Position {x = 1, y = 3}, energy = 10},
                     Octopus {position = Position {x = 2, y = 3}, energy = 10},
                     Octopus {position = Position {x = 3, y = 3}, energy = 10},
                     Octopus {position = Position {x = 4, y = 3}, energy = 4},
                     Octopus {position = Position {x = 0, y = 4}, energy = 3},
                     Octopus {position = Position {x = 1, y = 4}, energy = 4},
                     Octopus {position = Position {x = 2, y = 4}, energy = 5},
                     Octopus {position = Position {x = 3, y = 4}, energy = 4},
                     Octopus {position = Position {x = 4, y = 4}, energy = 3}
                   ]

  it "totalFlashes" $ do
    totalFlashes testInput 100 `shouldBe` 1656

main = hspec spec
