name:                Advent-of-Code-y2021
version:             0.1.0.0
github:              "borisskert/Advent-of-Code-y2021"
license:             BSD3
author:              "Boris Skert"
maintainer:          "boris.skert@gmail.com"
copyright:           "2021 Boris Skert"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/borisskert/Advent-of-Code-y2021#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Advent-of-Code-y2021-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Advent-of-Code-y2021

tests:
  Advent-of-Code-y2021-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Advent-of-Code-y2021
